### ISSUE TITLE
Project no longer runs as missing multipart dependency

### ISSUE THREAD

**Issue by ardelio** [dgodd/concourse-summary#21]
The project no longer runs and produces the following error:

```
root@f64be50113e0:/app# crystal run src/concourse-summary.cr
Error in src/concourse-summary.cr:2: while requiring "kemal"

require "kemal"
^

in lib/kemal/src/kemal.cr:2: while requiring "multipart": can't find file 'multipart' relative to '/app/lib/kemal/src'

require "multipart"
^
```

Adding multipart as a dependency in `shard.yml` fixes the issue:

```yml
dependencies:
  kemal:
    github: sdogruyol/kemal
    branch: master
  multipart:
    github: RX14/multipart.cr
    branch: master
```

I would raise a PR, unsure if this is the correct approach as am not familiar with Crystal
